import { readJSON } from 'fs-extra';
import { cleanObject } from './clean-object';

export interface OSSLibrary {
    readonly id: string;
    readonly name: string;
    readonly version: string;
    readonly npm: string;
    readonly license: string;
    readonly licenseText?: string;
}

interface RawOSSLibrary {
    readonly name: string;
    readonly version: string;
    readonly author?: string;
    readonly repository: string | null;
    readonly source: string;
    readonly license: string;
    readonly licenseText: string | null;
}

/**
 * @param licensesFile - file generated by the webpack-license-plugin package
 */
export async function getOSSLibraries({
    licensesFile,
}: {
    licensesFile: string;
}): Promise<OSSLibrary[]> {
    const rawLibraries: RawOSSLibrary[] = await readJSON(licensesFile);
    const ossLibraries = rawLibraries.map(
        ({ name, version, license, licenseText }) => {
            return {
                id: `${name}@${version}`,
                name,
                version,
                npm: `https://www.npmjs.com/package/${name}`,
                license,
                licenseText: licenseText ?? undefined,
            };
        }
    );

    return cleanObject(ossLibraries);
}
