export const shortId = (id: string) =>
	id
		.split(".")
		// Remove declaration kind specifiers starting with `+` prefix
		// to maintain compatibility with declaration IDs generated by `tsdoc`.
		.filter((part) => !part.startsWith("+"))
		.join(".");
