export function shortId(id: string): string {
  return (
    id
      .split(".")
      // Remove declaration kind specifiers starting with the `+` prefix
      // to maintain compatibility with declaration IDs generated by `tsdoc`.
      .filter((part) => !part.startsWith("+"))
      .join(".")
  );
}
